global:
  scrape_interval: 4s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090', '192.168.0.230:4000', '192.168.31.238:4000', 'host.docker.internal:4000']
